#pragma once

#include "pch.h"

namespace GloVar {

	namespace Ioctl {

		// (..., ..., METHOD_BUFFERED, FILE_ANY_ACCESS)

		const DWORD IOCTL_HYROAPI_TEST = \
			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, 0, 0);

    const DWORD IOCTL_HYROAPI_EPT_ADD = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, 0, 0);

    const DWORD IOCTL_HYROAPI_EPT_REMOVE = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, 0, 0);

    const DWORD IOCTL_HYROAPI_EPT_ENABLE = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, 0, 0);

    const DWORD IOCTL_HYROAPI_EPT_DISABLE = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, 0, 0);

    const DWORD IOCTL_HYROAPI_EPT_MODIFY = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, 0, 0);

    const DWORD IOCTL_HYROAPI_GENERAL_GET_PHYSICAL_ADDRESS = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, 0, 0);

    const DWORD IOCTL_HYROAPI_GENERAL_ALLOC_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, 0, 0);

    const DWORD IOCTL_HYROAPI_GENERAL_FREE_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, 0, 0);

    const DWORD IOCTL_HYROAPI_GENERAL_COPY_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, 0, 0);

    const DWORD IOCTL_HYROAPI_GENERAL_EXECUTE_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80a, 0, 0);

    const DWORD IOCTL_HYROAPI_GUEST_GENERAL_COPY_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80b, 0, 0);

    const DWORD IOCTL_HYROAPI_GUEST_GENERAL_EXECUTE_NONPAGED_BUFFER = \
      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80c, 0, 0);

		extern HANDLE hDevice;
	}

}